// <auto-generated />
namespace JTimev2.Migrations.ApplicationDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddFinancialToTimesheet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFinancialToTimesheet));
        
        string IMigrationMetadata.Id
        {
            get { return "201702190514163_AddFinancialToTimesheet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
